# Generated by Django 3.2.15 on 2024-12-17 13:18

import Formulario.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('numero_ingreso', models.CharField(blank=True, default='', max_length=100)),
                ('nombre_Proyecto', models.CharField(blank=True, default='', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('visita', models.FileField(blank=True, null=True, upload_to=Formulario.models.content_file_name_adjunto)),
                ('fecha_visita', models.DateTimeField(blank=True, null=True)),
                ('terreno', models.FileField(blank=True, null=True, upload_to=Formulario.models.content_file_name_adjunto)),
                ('fecha_terreno', models.DateTimeField(blank=True, null=True)),
                ('solicitud_au', models.FileField(blank=True, null=True, upload_to=Formulario.models.content_file_name_adjunto)),
                ('fecha_solicitud_au', models.DateTimeField(blank=True, null=True)),
                ('factibilidad', models.FileField(blank=True, null=True, upload_to=Formulario.models.content_file_name_adjunto)),
                ('fecha_factibilidad', models.DateTimeField(blank=True, null=True)),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'iniciativa',
                'verbose_name_plural': 'iniciativas',
            },
        ),
    ]
