# Generated by Django 3.2.15 on 2024-12-17 14:47

import Formulario.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
            },
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='Estado',
            field=models.CharField(blank=True, default='En Proceso', max_length=100),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='analisis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='asamblea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='asamblea_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=Formulario.models.content_file_asamblea_adjunto),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='asamblea_analisis',
            field=models.FileField(blank=True, null=True, upload_to=Formulario.models.content_file_analisis_adjunto),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='factibilidad_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=Formulario.models.content_file_factibilidad_adjunto),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='fecha_analisis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='fecha_asamblea',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='solicitud_au_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=Formulario.models.content_file_au_adjunto),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='terreno_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=Formulario.models.content_file_terreno_adjunto),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='visita_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=Formulario.models.content_file_name_adjunto),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='factibilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='solicitud_au',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='terreno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='visita',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='departamento_iniciativa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=Formulario.models.content_file_ini_depa_adjunto)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='Formulario.departamento')),
                ('id_iniciativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iniciativas', to='Formulario.iniciativa')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
            },
        ),
    ]
