# Generated by Django 3.2.15 on 2024-12-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0003_rename_asamblea_analisis_iniciativa_analisis_adjunto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iniciativa',
            old_name='nombre_Proyecto',
            new_name='nombre_proyecto',
        ),
    ]
