# Generated by Django 3.2.15 on 2024-12-26 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Formulario', '0005_auto_20241218_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ini_user',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('categoría', models.TextField(blank=True, null=True)),
                ('id_iniciativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ini', to='Formulario.iniciativa')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
