# Generated by Django 3.2.15 on 2025-01-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0007_bnup_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnup_ingreso',
            name='unidad_técnica',
            field=models.CharField(blank=True, choices=[('', ''), ('Direcciones de Obras Municipales', 'DOM'), ('Asesoría Urbana', 'AU')], default='', max_length=100),
        ),
    ]
