# Generated by Django 3.2.15 on 2025-01-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0008_alter_bnup_ingreso_unidad_técnica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bnup_ingreso',
            name='estado',
            field=models.TextField(blank=True, default='EN ESPERA'),
        ),
        migrations.AlterField(
            model_name='bnup_ingreso',
            name='unidad_técnica',
            field=models.CharField(blank=True, choices=[('Direcciones de Obras Municipales', 'DOM'), ('Asesoría Urbana', 'AU'), ('', '')], default='', max_length=100),
        ),
        
    ]
