# Generated by Django 3.2.15 on 2025-01-10 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0009_auto_20250110_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnup_ingreso',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Formulario.funcionario'),
        ),
        migrations.AlterField(
            model_name='bnup_ingreso',
            name='unidad_técnica',
            field=models.CharField(blank=True, choices=[('Asesoría Urbana', 'AU'), ('Direcciones de Obras Municipales', 'DOM'), ('', '')], default='', max_length=100),
        ),
    ]
