# Generated by Django 3.2.15 on 2025-01-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0011_remove_bnup_ingreso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnup_ingreso',
            name='unidad_técnica',
            field=models.CharField(blank=True, choices=[('', ''), ('Asesoría Urbana', 'AU'), ('Direcciones de Obras Municipales', 'DOM')], default='', max_length=100),
        ),
    ]
