# Generated by Django 3.2.15 on 2025-01-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0012_alter_bnup_ingreso_unidad_técnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnup_ingreso',
            name='estado',
            field=models.TextField(blank=True, default='EN ESPERA'),
        ),
        migrations.AlterField(
            model_name='bnup_ingreso',
            name='unidad_técnica',
            field=models.CharField(blank=True, choices=[('Direcciones de Obras Municipales', 'DOM'), ('Asesoría Urbana', 'AU'), ('', '')], default='', max_length=100),
        ),
    ]
